### ISSUE TITLE
Second rank card

### ISSUE THREAD

**Issue by SapphireDisD** [Ranker-Team/Ranker#4]
**Rank card deserves a second design for people to be able to choose**

Here is the design we will be working on, made by Fleuron from Microsoft Community:
![image](https://user-images.githubusercontent.com/88066694/133538518-d0e3c7c2-71f6-49ff-a86d-dffa4225d82e.png)

I assign this to @SapphireDisD

**Comment by dongle-the-gadget** [comment]
Also do you have a background for now? It currently doesn't, which causes an exception to throw with `!rank`. I temporarily commented the background adding code.

**Comment by SapphireDisD** [comment]
I'm completely going to rewrite it.

**Comment by dongle-the-gadget** [comment]
Oh

**Comment by dongle-the-gadget** [comment]
And btw, isn't the bottom part supposed to be a progress bar to the next XP?

**Comment by SapphireDisD** [comment]
> And btw, isn't the bottom part supposed to be a progress bar to the next XP?

I think so

**Comment by SapphireDisD** [comment]
I forgot to close this lol

**Comment by dongle-the-gadget** [comment]
Laughing out loud

**Comment by SapphireDisD** [comment]
wat

**Comment by dongle-the-gadget** [comment]
Oh nothing nothing.
