### ISSUE TITLE
Implement missing features

### ISSUE THREAD

**Issue by dongle-the-gadget** [Ranker-Team/Ranker#9]
# Priority notice
This list is created by me and prioritized by me, feel free to correct me.

# High priority
Bot should not be considered "finished" without these.
- [x] MEE6 migration
- [x] Rank card (#4)
- [x] Web leaderboard (https://github.com/Ranker-Team/Website)
- [x] Role assignment
- GitHub Community guidelines
   - [x] README
   - [x] License
   - [x] Code of Conduct
   - [x] Contributing guidelines
   - [x] Issue template

# Low priority
Features that can be missing in the first release, but can be useful.
- Customizability
   - [x] Leaderboard banner
   - [x] XP range
 - [x] Docker (initial support implemented in #25, thanks Eri)
 - [x] Pull request template (GItHub Community guidelines)

**Comment by dongle-the-gadget** [comment]
In my opinion we should avoid database changes to prevent conflicts with the older version.

**Comment by SapphireDisD** [comment]
> In my opinion we should avoid database changes to prevent conflicts with the older version.

Ironically I'm doing one.

**Comment by dongle-the-gadget** [comment]
> > In my opinion we should avoid database changes to prevent conflicts with the older version.
> 
> Ironically I'm doing one.

Well fine for now. It's just in Development so we could mess up the code whatever way we want to.

**Comment by itsWindows11** [comment]
> We're only missing `Rank card customization`. I'll be working on it. I'm planning it.

Are there some updates on this?

**Comment by SapphireDisD** [comment]
> > We're only missing `Rank card customization`. I'll be working on it. I'm planning it.
> 
> Are there some updates on this?

No idea of what to do

**Comment by itsWindows11** [comment]
aaaaaa where rank card customization???

**Comment by SapphireDisD** [comment]
> aaaaaa where rank card customization???

i forgor 💀

**Comment by SapphireDisD** [comment]
👀👀👀

**Comment by mikepattyn** [comment]
👀

**Comment by SapphireDisD** [comment]
soon

**Comment by SapphireDisD** [comment]
hopefully this week

**Comment by SapphireDisD** [comment]
AAAAAAAA but soon soon soon this time i swear

**Comment by SapphireDisD** [comment]
yeah never
